name: 🕸️ Deploy app to GKE

on:
  push:
    tags:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v2

    - name: 🔨 Build .env from GitHub secrets
      run: |
        echo "DATABASE_URL='${{ secrets.DATABASE_URL }}'" >> .env
        echo "SENDINBLUE_API_KEY='${{ secrets.SENDINBLUE_API_KEY }}'" >> .env
        echo "FRONTEND_URL='${{ secrets.FRONTEND_URL }}'" >> .env

    - name: 🗝️ Create SSL keys from secrets
      run: |
        echo "${{ secrets.PK_SERVICE }}" > ./ssl/service-auth-public.pem
        echo "${{ secrets.SK_SERVICE }}" > ./ssl/service-auth-private.pem
    
    - name: 🐳 Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: 👨‍💼 Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: 🔨 Build and push Docker image
      run: docker buildx build --push --tag mcamus9/ffc-notifications-docker .
    
    - name: 🔐 Login to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 🌐 Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 📦 Install GKE auth plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin

    - name: 🔐 Get GKE credentials
      uses: 'google-github-actions/get-gke-credentials@v1'
      with:
        cluster_name: 'fury-fight-club'
        location: 'europe-west1'
    
    - name: ⚙️ Configure Docker credentials for GCR
      run: gcloud auth configure-docker
    
    - name: ✈️ Deploy to GKE
      run: |
        gcloud container clusters get-credentials fury-fight-club --region europe-west1 --project fury-fight-club-386613
        kubectl set image deployment/ffc-notifications-deployment ffc-notifications=mcamus9/ffc-notifications-docker:latest
